webtalk_init -webtalk_dir E:/8-IITG Summer Internship/3-Verilog Files/4-bits/4-bits.sim/sim_1/behav/xsim/xsim.dir/TestbenchGeneral_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Aug 17 14:43:28 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0e9ee4f0-d34a-45ee-8ca5-a785a50edc12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "954d70c4304841afa8691180d0120535" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "153" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6644_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3015894590 -regid "" -xml E:/8-IITG Summer Internship/3-Verilog Files/4-bits/4-bits.sim/sim_1/behav/xsim/xsim.dir/TestbenchGeneral_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/8-IITG Summer Internship/3-Verilog Files/4-bits/4-bits.sim/sim_1/behav/xsim/xsim.dir/TestbenchGeneral_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/8-IITG Summer Internship/3-Verilog Files/4-bits/4-bits.sim/sim_1/behav/xsim/xsim.dir/TestbenchGeneral_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
